services:
  mediaflick-plexlocalscan-api:
    build: .
    user: 1000:1000
    container_name: mediaflick-plexlocalscan-api
    ports:
      - "3000:3000"
    volumes:
      - /mnt/zurg/tvseries:/mnt/zurg/tvseries
      - /mnt/zurg/movies:/mnt/zurg/movies
      - /mnt/organized/tvseries:/mnt/organized/tvseries
      - /mnt/organized/movies:/mnt/organized/movies
      - /opt/mediaflick:/app/config
      - /opt/mediaflick/logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://localhost:5000
      - NODE_ENV=production
      - CORS_ORIGINS=http://localhost:3000
      - API_URL=http://localhost:5000/api
      - SIGNALR_URL=http://localhost:5000/hubs
    restart: unless-stopped
