services:
  mediaflick:
    container_name: mediaflick
    build: .
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - /mnt/zurg:/mnt/zurg:rshared
      - /mnt/organized:/mnt/organized
      - /opt/mediaflick:/app/config
      - /opt/mediaflick/logs:/app/logs
      - /opt/mediaflick/cache:/.next/cache
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://localhost:5000
      - NODE_ENV=production
      - CORS_ORIGINS=http://localhost:3000
      - API_URL=http://localhost:5000/api
      - SIGNALR_URL=http://localhost:5000/hubs
    restart: on-failure
    healthcheck:
      test: ["CMD", "test", "-f", "/mnt/zurg/version.txt"]
      interval: 5s
      timeout: 2s
      retries: 30
