import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import HeadBar from "@/components/HeadBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Media Flick",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-blue-100 via-violet-100 to-purple-100 dark:from-blue-950 dark:via-violet-950 dark:to-purple-950`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="w-full border-b border-border">
            <div className="mx-auto max-w-7xl border-x border-border px-4">
              <HeadBar />
            </div>
          </div>
          <main className="mx-auto max-w-7xl min-h-[calc(100vh-4rem)] border-x border-border px-4">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
