import type { Metadata } from 'next'

import HeadBar from '@/components/HeadBar'
import { ThemeProvider } from '@/components/theme-provider'

import './globals.css'

export const metadata: Metadata = {
    title: 'Meta Flick',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-background font-sans text-foreground antialiased">
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <div className="sticky top-0 z-50">
                        <HeadBar />
                    </div>
                    <main className="min-h-[calc(100vh-4rem)] border-x border-border px-4">{children}</main>
                </ThemeProvider>
            </body>
        </html>
    )
}
